### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/AngularCorrelationUtility#10]
While investigating Issue #9, did some spot checks in comparison to the Geant code written by Evan. Found some inconsistencies that were not entirely attributable to Issue #9, where the two codes produced different a2 and a4 coefficients given identical inputs. Since the code for this page came from the Geant code, this is troubling.

4->2->0 with 0 mixing (and L1a=2 and L1b=3) gives the correct result in both cases though.

**Comment by SmithJK** [comment]
I've tracked the difference down to the Wigner6j function. Still tracking.

**Comment by SmithJK** [comment]
This difference can be attributed to the changes made to the code in the commit "some simple optimizations" from December 1. Specifically, the changes made to the `ClebschGordan` function in `angular_corr.js`. An empty `if` statement was changed to a set of `if` and then `else if` statements. The original code was:
```
for(k = 0 ; k <= 99 ; k++ ){
        if( (j1+j2-j-k < 0) || (j-j1-m2+k < 0) || (j-j2+m1+k < 0) || (j1-m1-k < 0) || (j2+m2-k < 0) ){}
        else{
            term = Factorial(j1+j2-j-k)*Factorial(j-j1-m2+k)*Factorial(j-j2+m1+k)*Factorial(j1-m1-k)*Factorial(j2+m2-k)*Factorial(k);
            if((k%2) == 1){
                term = -1*term;
            }
            sum = sum + 1.0/term;
        }
    }
```
Now it is:
```
for(k = 0 ; k <= 99 ; k++ ){
        if( (j1+j2-j-k < 0) || (j1-m1-k < 0) || (j2+m2-k < 0) )
            //no further terms will contribute to sum, exit loop
            break
        else if( (j-j1-m2+k < 0) || (j-j2+m1+k < 0)  )
            //jump ahead to next term that will contribute
            k = Math.max(Math.max(j-j1-m2, j-j2+m1) - 1, k);
        else{
            term = Factorial(j1+j2-j-k)*Factorial(j-j1-m2+k)*Factorial(j-j2+m1+k)*Factorial(j1-m1-k)*Factorial(j2+m2-k)*Factorial(k);
            if((k%2) == 1){
                term = -1*term;
            }
            sum = sum + 1.0/term;
        }
```
I think it's actually the jump ahead to the next term that is causing the problem; when I remove that, the comparison between Geant and the website is exact. @BillMills, I'm not certain what optimization you were going for here, so I can't tell if there's a typo.

**Comment by BillMills** [comment]
Ah yes, I think I see - in my second clause, I skip `k` ahead to to one less than the max of `j-j1-m2` and `j-j2+m1`, so it'll be equal to the max on the next iteration of the k loop (thus skipping us ahead to the next loop that will actually do something). But, if `(j-j1-m2+k < 0) || (j-j2+m1+k < 0)` is true and k is positive, then `j-j1-m2` and `j-j2+m1` must be negative, so we actually want the negative *min* (ie max magnitude) of them.

If you change to
```
k = Math.max(-Math.min(j-j1-m2, j-j2+m1) - 1, k);
```

does your problem go away? Hard to tell just by staring at the algebra, let me know.

**Comment by SmithJK** [comment]
Yes, this seems to fix it.

**Comment by SmithJK** [comment]
Fixed with recent commit.
