### ISSUE TITLE
recalculate trigger

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/AngularCorrelationUtility#4]
@SmithJK - going through this project now, looks pretty good under the hood! I noticed that `recalculate()` doesn't seem to get called when changing the L[1,2][a,b] radios. This is easy to fix, but let me know if there's anything more to it than just calling `recalculate()`.

**Comment by SmithJK** [comment]
That should be it.

**Comment by BillMills** [comment]
Thanks! Just wanted to make sure there wasn't something fancier than I at first appreciated.
