### ISSUE TITLE
comments plz

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/AngularCorrelationUtility#5]
HI @SmithJK,

Here's a first pass at a layout redux of this tool: http://griffincollaboration.github.io/AngularCorrelationUtility/ ; if you could please make sure I didn't break anything horribly, I would be much obliged. A few comments:

 - This rebuild *looks* a lot different, but it's entirely untouched from your original work under the hood; this really just modernizes the html and lightens the dependency load.
 - Things get awful slow when all the J values are set to high numbers, courtesy of the 6 nested for loops in `Wigner6j`; I'd like to try streamlining this. Do you have any ideas for speeding this up? Any symmetry arguments, or opportunities to call this function a strict minimum of times? I suspect we might get some mileage out of caching (after calculating the result the slow way for a set of input variables, put that result in a lookup table so we don't ever have to do it again), but I wanted to see if you have any insight into this first.
 - note that setting custom a2 and a4 values now raises a warning to point out that they no longer correspond to the requested parameters in the rest of the UI; this is the most ham-fisted way to solve this problem, let me know if you can think of something more elegant.
 - Notice the References section at the bottom; please feel free to add any references you see fit.

**Comment by SmithJK** [comment]
After a bit of playing, I don't see anything broken horribly.
* I noticed the slow-down for high J values as well. Practically, I don't think this will be much of a problem - most of the time, multipolarities are small. I don't have any more elegant solutions in mind. Caching it would be helpful even for the smaller multipolarities - it might make oninput calculation of the dygraph values possible in lieu of onchange. Could it be done after changing the J values? 
* I like the warning. Could change the colors in the dygraph as well, though I think the text box is prominent enough.

**Comment by BillMills** [comment]
OK, today's push introduces some simple optimizations:

 - factorials are now cached
 - `ClebschGordan` avoids unnecessary loop iterations
 - `Wigner3j` doesn't check for sensible momenta (good idea to check - but we should factor this out into an independent test suite so we aren't doing it in a function we call a zillion times in the browser).

Totally colloquially, this saved about 1-1.5s or ~50% when setting J3 = 9 and subsequently L2B to 11.

Caching many-variable functions was not as successful as I hoped; the problem was that the lookup in a large key-value store became slower than the actual calculation. Might be able to overcome this with a fancier cache (some by-hand memory management in an arrayBuffer? Just a guess...).

One thing I finally sat down to try as part of this might interest C++ fans: [emscripten](http://kripken.github.io/emscripten-site/) transpiles C++ functions to optimized JavaScript, with a demonstrated slow-down as good as only a factor of 2 over native compiled code - pretty good! I haven't managed to coax a speedup out of this over the optimizations described above, but I may just be doing it wrong so far; more generally, this could be interesting for building tools like this in future, where C implementations of key functionality already exist.
