### ISSUE TITLE
a2 / a4 as a function of mixing ratio

### ISSUE THREAD

**Issue by BillMills** [GRIFFINCollaboration/AngularCorrelationUtility#6]
Today's push introduces the plots of a2 and a4 as a function of mixing ratio as requested by @SmithJK [over here](https://github.com/GRIFFINCollaboration/griffin-website/issues/2). Couple points:

 - Getting this right necessitated introducing a unit test suite; we're using qunit again as per the beam companion explorer. If anything seems questionable and needs to be tested, or if there are any sanity checks we can impose on the physics, this is the place to add them.
 - do please have a look and make sure the a2 and a4 plots make sense; the test suite makes sure the number reported in the sidebar will come out the same as the corresponding cell on the plot, but that's just a single spot check for a single set of parameters.
 - plotly.js just open sourced itself a few weeks ago, and it looks pretty good! But, there are still a few rough edges; but, hopefully nothing we can't live with until they patch (or write some docs).

**Comment by SmithJK** [comment]
Just as the mixing ratio slider is disabled when only a single angular momentum value is available, these plots should do the same. Perhaps in that case, the 2D plots turn into 1D plots of a2 vs. unconstrained mixing ratio and a4 vs. unconstrained mixing ratio?

**Comment by SmithJK** [comment]
They look pretty. I like the palette choice.

**Comment by BillMills** [comment]
Pretty is what I'm shooting for :)

So just to make sure I get it, what you want is when, for example, L2a and L2b are the same, you want to replace the 2D plots with 1D plots which are effectively a slice of the 2D plots along L2a/l2b = 0. Shouldn't be a problem if I've understood it correctly.

**Comment by SmithJK** [comment]
Yep, exactly.

**Comment by BillMills** [comment]
*et voila* - let me know if this is working for you, and as always, it's a very good idea to think up two or three sanity checks and check them.
