### ISSUE TITLE
Save button on 2D plot bug

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/AngularCorrelationUtility#7]
Save button on 2D plot produces Plotly "Uh oh. An error occurred while processing this request." page.

**Comment by BillMills** [comment]
You mean the little floppy? That's for exporting to the cloud, which requires a service contract (nope) - to save the image to your computer, use the little camera (in chrome - bugged in FF).

**Comment by BillMills** [comment]
oh well lucky us - looks like that ff bug is fixed at plotly 1.5.0.
